name: Weather Bot

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '55 22 * * *'

env:
  API_KEY: ${{ secrets.API_KEY }}
  WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
  CITY: ${{ secrets.CITY }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install stable toolchain
      uses: dtolnay/rust-toolchain@stable
    - name: Build
      run: cargo run --release
